# GolangCI-Lint 配置文件
# 用于自动化代码审查和代码质量检查

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-line: true
  print-linter-name: true

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: cloud-platform-api
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: cloud-platform-api
  golint:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        # 检查数字字面量
        checks: argument,case,condition,operation,return,assign
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  # 默认启用的linters
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  # 禁用的linters
  disable:
    - gochecknoglobals
    - gochecknoglobals
    - interfacer
    - scopelint
    - maligned

issues:
  # 排除规则
  exclude-rules:
    # 排除测试文件中的某些检查
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocyclo
        - lll
    
    # 排除生成的代码
    - path: ".*\\.pb\\.go"
      linters:
        - all
    
    # 排除vendor目录
    - path: vendor/
      linters:
        - all
    
    # 排除某些特定的错误
    - text: "exported (var|const|func|type) [A-Za-z0-9_]+ should have comment or be unexported"
      linters:
        - golint
    
    # 排除某些特定的函数长度限制
    - text: "function .* is too long"
      linters:
        - funlen

  # 最大问题数量
  max-issues-per-linter: 0
  max-same-issues: 0

  # 排除目录
  exclude-dirs:
    - vendor
    - .git
    - node_modules
    - storage
    - logs
    - temp

  # 排除文件
  exclude-files:
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"
